name: CI

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  linux-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: '18'
          
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Haxelibs
        run: |
          haxelib --quiet install lime 7.9.0
          haxelib --quiet install openfl 9.1.0
          haxelib --quiet install flixel
          haxelib --quiet --never run lime setup
          haxelib --quiet install flixel-ui
          haxelib --quiet install flixel-addons
          haxelib --quiet install hscript
          haxelib --quiet install hxcpp-debug-server
          haxelib --quiet git flxanimate https://github.com/Dot-Stuff/flxanimate.git
          haxelib --quiet git hxCodec https://github.com/polybiusproxy/hxCodec.git
          haxelib --quiet git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools.git

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib set lime 7.9.0
          haxelib set openfl 9.1.0
          haxelib list
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: haxelib run lime build linux -release

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild-release
          path: export/release/linux/bin/
